# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartogenAi
                                 A QGIS plugin
 Cartogen AI -- spatial AI that plans, executes, and shows its work inside QGIS
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-06
        copyright            : (C) 2026 by Alaa Alshoubaki
        email                : alaa.alshoubaki@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys
import types
import importlib

# Make the cartogen_ai.core namespace package (src/cartogen_ai/core/) importable.
#
# This was a bare `sys.path.insert(0, src)` whose own comment flagged it as
# unverified in live QGIS. It is now verified, and it was insufficient: the
# plugin failed at runtime with "No module named 'cartogen_ai.core'".
# Reproduced outside QGIS, three states defeat the plain insert, all producing
# that same message:
#
#   1. A REGULAR package or module named cartogen_ai anywhere on sys.path wins
#      over our PEP-420 namespace portion REGARDLESS of sys.path order, so
#      inserting at position 0 does not help. (A stale cartogen_ai.py from the
#      pre-restructure tree is exactly this -- see plugin_main.py's docstring.)
#   2. A bare directory named cartogen_ai (no core/) on sys.path while our src/
#      is absent.
#   3. A stale cartogen_ai left in sys.modules by an earlier or failed load, or
#      a plugin reload -- sys.modules is consulted before any path search, so
#      the insert is never used.
#
# Distinguishing detail: if src/ were merely missing, the error would be
# "No module named 'cartogen_ai'" WITHOUT the .core suffix.
#
# _bootstrap_namespace() handles all three and verifies by actually importing.
_PLUGIN_DIR = os.path.dirname(os.path.abspath(__file__))
_SRC_DIR = os.path.join(_PLUGIN_DIR, "src")
_PKG_DIR = os.path.join(_SRC_DIR, "cartogen_ai")


def _evict_cartogen_modules():
    for name in [n for n in list(sys.modules)
                 if n == "cartogen_ai" or n.startswith("cartogen_ai.")]:
        del sys.modules[name]


def _bootstrap_namespace():
    """Make cartogen_ai.core importable deterministically. Returns how it resolved."""
    norm = os.path.normcase(os.path.abspath(_SRC_DIR))
    sys.path[:] = [p for p in sys.path
                   if os.path.normcase(os.path.abspath(p or ".")) != norm]
    sys.path.insert(0, _SRC_DIR)

    # Evict unconditionally, not only when the cached package came from a
    # different path. This used to check the path, and an in-place upgrade
    # slipped through it: Install from ZIP over a running rc4 re-imports this
    # package from the SAME folder, so rc4's already-imported
    # cartogen_ai.infrastructure.settings_keys stayed cached while rc5's
    # freshly imported modules asked it for names it never had -- reported
    # live on QGIS 4.2.2 as "Failed to open panel: cannot import name
    # 'SETTINGS_PROJECT_INSPECTOR_ENABLED'", and reproduced by extracting the
    # real rc4 zip, importing it, then extracting rc5 over it. QGIS's own
    # unloadPlugin only drops modules named after the plugin folder
    # ("cartogen-ai"), never our separate cartogen_ai.* tree, so nothing else
    # clears them. This file runs once per (re)load, so on a first load the
    # eviction is a no-op.
    _evict_cartogen_modules()

    importlib.invalidate_caches()

    try:
        importlib.import_module("cartogen_ai.core")
        return "resolved-normally"
    except ImportError:
        # sys.modules is checked before any finder, so an explicit registration
        # cannot be beaten by a shadowing package.
        _evict_cartogen_modules()
        ns = types.ModuleType("cartogen_ai")
        ns.__path__ = [_PKG_DIR]
        sys.modules["cartogen_ai"] = ns
        importlib.invalidate_caches()
        importlib.import_module("cartogen_ai.core")
        return "forced-explicit"


try:
    _BOOTSTRAP_MODE = _bootstrap_namespace()
    print(f"[CartogenAi] namespace bootstrap: {_BOOTSTRAP_MODE} ({_PKG_DIR})")
except Exception as _e:  # pragma: no cover - diagnostic path
    _BOOTSTRAP_MODE = f"FAILED: {_e}"
    print(f"[CartogenAi] namespace bootstrap FAILED: {_e}")
    print(f"[CartogenAi]   expected package dir: {_PKG_DIR}")
    print(f"[CartogenAi]   exists: {os.path.isdir(_PKG_DIR)}")


def classFactory(iface):
    """Load CartogenAi class from file plugin_main.py.

    The plugin's main class used to live in a file named cartogen_ai.py --
    renamed to plugin_main.py because that name collided with the
    cartogen_ai.core namespace package above: once this repo's own root
    directory is on sys.path, a regular module named cartogen_ai.py there
    always wins over the src/cartogen_ai/ namespace portion when Python
    resolves `import cartogen_ai`, which broke every `from
    cartogen_ai.core.agent... import X` call throughout the codebase.
    Confirmed live via the test suite (31 import failures) before this
    rename -- see docs/archive/MULTITIER_REPO_ARCHITECTURE_SPEC.md #3 and
    docs/BUG_TRACKER.md.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .plugin_main import CartogenAi
    return CartogenAi(iface)
