# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartogenAi
                                 A QGIS plugin
 Cartogen AI -- spatial AI that plans, executes, and shows its work inside QGIS
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-06
        copyright            : (C) 2026 by Alaa Alshoubaki
        email                : alaa.alshoubaki@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load CartogenAi class from file CartogenAi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cartogen_ai import CartogenAi
    return CartogenAi(iface)
